version: '3.7'

services:
  gitapp_db:
    image: postgres
    container_name: gitapp_db
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=gitapp
    restart: always
    ports:
      - "6060:5432"
    volumes:
      - ./database:/docker-entrypoint-initdb.d/
    networks:
      gitapp:

  gitapp_server:
    container_name: gitapp_server
    build: ./api
    depends_on:
      - gitapp_db
    networks:
      gitapp:
    ports:
      - "4040:4040"
    volumes:
      - ./api:/app
    environment:
      FLASK_ENV: development

  gitapp_client:
    container_name: gitapp_client
    build: ./client
    ports:
      - "8080:3000"
    networks:
      gitapp:
    volumes:
      - ./client:/app

networks:
  gitapp: